/**
 * DB helpers for the session-less ChatGPT-as-signin path.
 *
 * Parallel to lib/openai-oauth-db.ts, but keyed on `anonymous_session_id`
 * (HTTPOnly cookie value) instead of `user_id` (the existing connect path's
 * key). The split keeps the two use cases from leaking concerns into each
 * other:
 *
 *   - openai-oauth-db.ts: post-signup connect from /settings. User exists.
 *     Operations are scoped by user_id (the authenticated session).
 *   - openai-signup-db.ts (this file): /signin first-time signup. User
 *     may not exist yet. Operations are scoped by anonymous_session_id
 *     during the polling window, then "graduate" to user_id on completion.
 *
 * Reuses `storeOAuthTokens` from openai-oauth-db.ts at the moment of
 * graduation — once we resolve a user_id, the existing helper handles
 * the encrypted-token write + token_version bump identically to the
 * connect path.
 *
 * USER RESOLUTION SEMANTICS
 * ─────────────────────────
 * `resolveSignupUser` is the load-bearing piece. Given a successful
 * device-code completion's claims + the cookie context from the browser,
 * it produces a stable user_id by either:
 *
 *   (a) Looking up an existing user by email
 *       - If they have a google_id but no openai_oauth_*: that's a user
 *         who previously signed in with Google. We link OpenAI to their
 *         existing account (don't create a duplicate). Apply partner /
 *         edge_verified cookies if present.
 *       - If they have openai_oauth_*: same user re-signing in. Apply
 *         partner cookie if not yet set; the storeOAuthTokens call later
 *         refreshes their tokens.
 *
 *   (b) INSERTing a new row when no match exists. Mirrors the
 *       lib/auth.ts signIn callback's new-user branch for Google:
 *       writes email, name (derived from email), partner, referred_by,
 *       edge_verified_email.
 *
 * In both cases the result is a single user_id that downstream code
 * (storeOAuthTokens, NextAuth Credentials authorize, signIn/jwt/session
 * callbacks) treats identically to a Google-created user. A
 * ChatGPT-authed Edge attendee and a Google-authed Edge attendee MUST be
 * indistinguishable by the time they reach /deploying — per Cooper's
 * Option-A spec.
 *
 * EDGE_VERIFIED COOKIE HANDLING
 * ─────────────────────────────
 * The signed cookie's email must match claims.email — exactly the same
 * check the Google path does (lib/auth.ts:43-48). If the cookie was
 * minted for `alice@edgecity.com` but the user signs in with ChatGPT
 * under `alice@personal.com`, we refuse to honor the cookie and log a
 * warn — they get the same "no partner tag" outcome as the Google
 * mismatch case.
 */
import crypto from "crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { logger } from "./logger";
import { tagUserAsPartner } from "./partner-tag";
import {
  verifyEdgeVerifiedCookie,
} from "./edge-verified-cookie";
import type { DeviceCodeStart, IdTokenClaims } from "./openai-oauth";

// ─── Types ───────────────────────────────────────────────────────────────

export interface SignupFlowRow {
  id: string;
  anonymous_session_id: string;
  provider: string;
  device_auth_id: string;
  user_code: string;
  verification_uri: string;
  interval_seconds: number;
  expires_at: string;
  status: "pending" | "completed" | "expired" | "denied" | "error";
  status_message: string | null;
  resolved_user_id: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface SignupCookieContext {
  partnerCookie: string | null;
  referralCode: string | null;
  edgeVerifiedCookieRaw: string | null;
}

export interface ResolveSignupUserResult {
  /** instaclaw_users.id — never null on success. */
  userId: string;
  /** True if this resolution INSERTed a new user; false if linked/refreshed. */
  isNewUser: boolean;
  /** True if a partner tag was applied (regardless of new vs existing user). */
  partnerApplied: boolean;
  /** True if edge_verified_email was successfully written. */
  edgeVerifiedApplied: boolean;
}

// ─── Flow row CRUD ───────────────────────────────────────────────────────

/**
 * Generate a fresh anonymous_session_id. 32 bytes of crypto-random ->
 * 64-char hex string. Stored in the openai_signup_session HTTPOnly cookie.
 */
export function generateAnonymousSessionId(): string {
  return crypto.randomBytes(32).toString("hex");
}

/**
 * Insert a new signup flow row. Anonymous_session_id is generated by the
 * caller (so the cookie can be set on the response BEFORE the DB write
 * commits — preserves the "set-then-write" ordering that prevents a
 * window where the cookie exists but the row doesn't).
 *
 * NOTE: no "create or reuse" semantics — every /signup/start call mints
 * a fresh anonymous_session_id, so concurrent clicks just create
 * independent flows. The dashboard connect path has "reuse pending"
 * because the user is a known entity; here we have nothing to dedupe by.
 */
export async function createSignupFlow(
  anonymousSessionId: string,
  started: DeviceCodeStart,
  supabase: SupabaseClient,
): Promise<SignupFlowRow> {
  const expiresAt = new Date(Date.now() + started.expiresInMs).toISOString();
  const intervalSeconds = Math.max(1, Math.round(started.intervalMs / 1000));

  const { data, error } = await supabase
    .from("instaclaw_oauth_signup_flows")
    .insert({
      anonymous_session_id: anonymousSessionId,
      provider: "openai_codex",
      device_auth_id: started.deviceAuthId,
      user_code: started.userCode,
      verification_uri: started.verificationUri,
      interval_seconds: intervalSeconds,
      expires_at: expiresAt,
      status: "pending" as const,
    })
    .select("*")
    .single();

  if (error || !data) {
    throw new Error(`createSignupFlow: insert failed: ${error?.message ?? "no row"}`);
  }
  return data as SignupFlowRow;
}

/**
 * Look up by anonymous_session_id. Returns null if not found. Service-role
 * client; no RLS — caller has already gated on the cookie being present.
 */
export async function getSignupFlow(
  anonymousSessionId: string,
  supabase: SupabaseClient,
): Promise<SignupFlowRow | null> {
  const { data, error } = await supabase
    .from("instaclaw_oauth_signup_flows")
    .select("*")
    .eq("anonymous_session_id", anonymousSessionId)
    .maybeSingle();

  if (error) {
    throw new Error(`getSignupFlow: read failed: ${error.message}`);
  }
  return (data as SignupFlowRow | null) ?? null;
}

/**
 * Mark the flow as completed and stamp the resolved user_id. Idempotent
 * write — re-running with the same args produces the same row state.
 */
export async function markSignupFlowCompleted(
  flowId: string,
  resolvedUserId: string,
  supabase: SupabaseClient,
): Promise<void> {
  const { error } = await supabase
    .from("instaclaw_oauth_signup_flows")
    .update({
      status: "completed",
      resolved_user_id: resolvedUserId,
      completed_at: new Date().toISOString(),
      status_message: null,
    })
    .eq("id", flowId);

  if (error) {
    throw new Error(`markSignupFlowCompleted: write failed: ${error.message}`);
  }
}

/**
 * Mark a non-completed terminal state (expired / denied / error). Best-effort:
 * caller catches and logs; failures here don't fail the user's flow because
 * the row is dead either way.
 */
export async function markSignupFlowFailed(
  flowId: string,
  status: "expired" | "denied" | "error",
  message: string | null,
  supabase: SupabaseClient,
): Promise<void> {
  const { error } = await supabase
    .from("instaclaw_oauth_signup_flows")
    .update({
      status,
      status_message: message?.slice(0, 500) ?? null,
      completed_at: new Date().toISOString(),
    })
    .eq("id", flowId);

  if (error) {
    throw new Error(`markSignupFlowFailed: write failed: ${error.message}`);
  }
}

// ─── User identity resolution ────────────────────────────────────────────

/**
 * Given a completed device-code result + the cookies from the browser,
 * find or create the user. The single source of truth for "who is this
 * person and what user_id do they get."
 *
 * Throws on hard failures (missing email in claims, DB errors that aren't
 * recoverable). Logs and degrades for recoverable issues (partner tag
 * fails — log + continue; edge cookie invalid — log + skip the field).
 *
 * Mirrors lib/auth.ts:signIn callback as closely as possible. When that
 * file changes, this one needs to be re-audited. Future P1: extract the
 * shared identity-resolution logic to a single helper that both callers
 * use.
 */
export async function resolveSignupUser(
  claims: IdTokenClaims,
  cookies: SignupCookieContext,
  supabase: SupabaseClient,
): Promise<ResolveSignupUserResult> {
  // 1. Required claim: email. Without it we can't identify the user.
  const email = (claims.email ?? "").trim().toLowerCase();
  if (!email) {
    throw new Error("resolveSignupUser: claims.email is missing — cannot create user");
  }

  // 2. Validate the edge_verified cookie. Same logic as lib/auth.ts:39-60.
  //    Cookie must (a) sign-verify, (b) be unexpired, (c) match claims.email.
  const edgeVerifiedResult = verifyEdgeVerifiedCookie(cookies.edgeVerifiedCookieRaw);
  const edgeVerifiedEmail =
    edgeVerifiedResult.ok &&
    edgeVerifiedResult.email &&
    edgeVerifiedResult.email === email
      ? edgeVerifiedResult.email
      : null;
  if (cookies.edgeVerifiedCookieRaw && !edgeVerifiedEmail) {
    logger.warn("resolveSignupUser: edge_verified cookie present but rejected", {
      route: "auth/openai/signup",
      reason: edgeVerifiedResult.reason,
      cookieEmail: edgeVerifiedResult.email,
      claimsEmail: email,
    });
  }

  // 3. Look up existing user by email.
  const { data: existing, error: lookupErr } = await supabase
    .from("instaclaw_users")
    .select("id, google_id, partner, edge_verified_email, openai_oauth_account_id")
    .eq("email", email)
    .maybeSingle();

  if (lookupErr) {
    throw new Error(`resolveSignupUser: lookup failed: ${lookupErr.message}`);
  }

  let userId: string;
  let isNewUser: boolean;

  if (existing) {
    // EXISTING USER — link or refresh.
    userId = existing.id as string;
    isNewUser = false;

    // Apply edge_verified_email update — same conditional as the Google
    // existing-user branch (lib/auth.ts:104-120). We OR-guard so we never
    // overwrite a different verified email on the row.
    if (edgeVerifiedEmail) {
      const { error: edgeWriteErr } = await supabase
        .from("instaclaw_users")
        .update({ edge_verified_email: edgeVerifiedEmail })
        .eq("id", userId)
        .or(
          `edge_verified_email.is.null,edge_verified_email.eq.${edgeVerifiedEmail}`,
        );
      if (edgeWriteErr) {
        logger.warn("resolveSignupUser: edge_verified_email write failed on existing-user", {
          userId,
          code: edgeWriteErr.code,
          error: String(edgeWriteErr.message),
          route: "auth/openai/signup",
        });
      }
    }
  } else {
    // NEW USER — INSERT row. Mirrors lib/auth.ts:205-213 new-user branch.
    //
    // Name derivation: OpenAI's id_token doesn't include the user's
    // display name. We derive from the email's local part (alice@x.com
    // → "alice") as a placeholder. Cooper's design philosophy: give the
    // user something readable now; they can edit later from settings.
    const derivedName = email.split("@")[0] || null;

    // Defensive note: google_id is intentionally NULL — this user signed
    // up via OpenAI device-code, not Google OAuth. The lib/auth.ts
    // session callback's google_id lookup will return nothing for this
    // user; the Credentials provider path lookups by id instead (see
    // the session callback update in this PR).
    const referralLowered = cookies.referralCode
      ? decodeURIComponent(cookies.referralCode).trim().toLowerCase()
      : null;

    const insertPayload: Record<string, unknown> = {
      email,
      name: derivedName,
      google_id: null,
      invited_by: null,
      referred_by: referralLowered,
    };
    if (cookies.partnerCookie) {
      insertPayload.partner = cookies.partnerCookie;
    }
    if (edgeVerifiedEmail) {
      insertPayload.edge_verified_email = edgeVerifiedEmail;
    }

    const { error: insertErr } = await supabase
      .from("instaclaw_users")
      .insert(insertPayload);

    if (insertErr) {
      // 23505 = unique violation. Possible causes:
      //   - email unique constraint: race with another signup using same email
      //   - edge_verified_email unique: someone else claimed this email
      //     between the gate and this callback (Edge dual-claim attempt)
      if (insertErr.code === "23505") {
        if (insertErr.message?.includes("edge_verified_email")) {
          // Retry without the edge column — same recovery as Google path
          // (lib/auth.ts:230-249). The user still gets an account; they
          // just lose the edge tag (the gate UI usually catches this
          // upstream and shows "already_claimed").
          logger.warn("resolveSignupUser: edge_verified_email already claimed, retrying without", {
            email,
            error: String(insertErr.message),
            route: "auth/openai/signup",
          });
          const retryPayload: Record<string, unknown> = {
            email,
            name: derivedName,
            google_id: null,
            invited_by: null,
            referred_by: referralLowered,
          };
          if (cookies.partnerCookie) {
            retryPayload.partner = cookies.partnerCookie;
          }
          const { error: retryErr } = await supabase
            .from("instaclaw_users")
            .insert(retryPayload);
          if (retryErr && retryErr.code !== "23505") {
            throw new Error(
              `resolveSignupUser: retry insert failed: ${retryErr.message}`,
            );
          }
        } else if (insertErr.message?.includes("email")) {
          // Race on email column — another concurrent signup. Re-fetch
          // and use whoever won.
          logger.warn("resolveSignupUser: email race detected, re-fetching", {
            email,
            route: "auth/openai/signup",
          });
        } else {
          throw new Error(`resolveSignupUser: insert failed: ${insertErr.message}`);
        }
      } else {
        throw new Error(`resolveSignupUser: insert failed: ${insertErr.message}`);
      }
    }

    // Re-fetch to get the newly-created (or race-winner's) id.
    const { data: created, error: refetchErr } = await supabase
      .from("instaclaw_users")
      .select("id")
      .eq("email", email)
      .single();
    if (refetchErr || !created) {
      throw new Error(
        `resolveSignupUser: re-fetch after insert failed: ${refetchErr?.message ?? "no row"}`,
      );
    }
    userId = created.id as string;
    isNewUser = true;
  }

  // 4. Apply partner tag (with skills propagation). Idempotent + non-blocking.
  //    tagUserAsPartner handles validation against VALID_PARTNERS and never
  //    throws — failures here don't block the signin.
  let partnerApplied = false;
  if (cookies.partnerCookie) {
    const result = await tagUserAsPartner(supabase, userId, cookies.partnerCookie);
    partnerApplied = result.ok && result.userUpdated;
    if (!result.ok) {
      logger.warn("partner-tag failed during openai signup (non-blocking)", {
        userId,
        partnerCookie: cookies.partnerCookie,
        error: result.error,
        route: "auth/openai/signup",
      });
    }
  }

  return {
    userId,
    isNewUser,
    partnerApplied,
    edgeVerifiedApplied: !!edgeVerifiedEmail,
  };
}
