/**
 * Source-of-truth constants for systemd user units deployed via
 * vm-manifest.ts:files[]. Every consumer (manifest entries, reconciler
 * sentinel checks, configureOpenClaw provision hooks) references these
 * constants — never literal strings in multiple places.
 *
 * See CLAUDE.md Rule 70 for the rationale on why these units exist,
 * the window selection, the RandomizedDelaySec sizing, and the rollback
 * mechanism.
 *
 * Original investigation: docs/postmortems/2026-05-28-typing-degradation-investigation.md
 * (the IR session that empirically proved gateway in-memory state
 * degrades silently after ~9h of accumulated Telegram fetch timeouts
 * and transport aborts, and that a graceful SIGTERM-clean restart
 * fully clears it).
 *
 * Any change to a unit-file body below propagates fleet-wide automatically
 * within ~15 minutes via the file-drift cron (Rule 47), and the reconciler
 * step `stepEnableDailyRestartTimer` detects the content drift via md5
 * comparison and triggers a daemon-reload + timer restart so the new
 * schedule (or whatever changed) takes effect without operator action.
 */

/**
 * The oneshot service that performs the actual restart. Triggered exclusively
 * by `openclaw-daily-restart.timer`; nothing else should invoke it.
 *
 * The use of `try-restart` (not `restart`) is load-bearing: it is a no-op
 * when openclaw-gateway is not currently running, which means hibernating
 * VMs (gateway intentionally stopped by suspend-check), crashed VMs in
 * StartLimit cooldown, and freshly-provisioned VMs whose gateway hasn't
 * been started for the first time yet are all silently and correctly
 * skipped. `restart` would START the gateway on those VMs, which is the
 * exact wrong behaviour.
 */
export const DAILY_RESTART_SERVICE_UNIT = `# Generated by InstaClaw platform — DO NOT EDIT MANUALLY.
# Source: instaclaw/lib/systemd-templates.ts (constant DAILY_RESTART_SERVICE_UNIT).
# Deployed by: instaclaw/lib/vm-manifest.ts:files[] (mode: overwrite).
# Manual edits are reverted on the next file-drift cron tick (~15 min).
#
# This unit performs a single graceful restart of openclaw-gateway and exits.
# It is triggered solely by openclaw-daily-restart.timer. See CLAUDE.md
# Rule 70 for the full rationale.

[Unit]
Description=Daily openclaw-gateway restart for state hygiene (CLAUDE.md Rule 70)
Documentation=https://github.com/coopergwrenn/clawlancer/blob/main/CLAUDE.md

[Service]
Type=oneshot

# try-restart is intentionally chosen over restart. The semantic difference:
#   - restart:     stops the unit, starts it. If the unit was not running,
#                  it gets STARTED.
#   - try-restart: stops the unit, starts it ONLY if it was running.
# Hibernating VMs, crashed VMs in cooldown, and freshly-provisioned VMs
# whose gateway has never started must NOT be woken / re-launched by a
# clock-driven hygiene timer. try-restart preserves their intentional
# stopped state. Verified against the 25 edge cases enumerated in the
# 2026-05-28 design doc (search Rule 70 / IR session).
ExecStart=/bin/systemctl --user try-restart openclaw-gateway.service

# Make the timer-driven restart cycle observable in the standard journal
# query: \`journalctl --user -u openclaw-daily-restart.service --since today\`.
# Without these, oneshot services log only the systemd-level Started/Succeeded
# transitions, which is sufficient but slightly less greppable.
StandardOutput=journal
StandardError=journal
`;

/**
 * The schedule that triggers the oneshot service above.
 *
 * Choice of 09:00 UTC ± 30min is global low-traffic for this user base:
 *   - 09:00 UTC = 05:00 EST = 02:00 PST = 10:00 CET = 18:00 JST.
 *   - For the predominantly US user base, both coasts are deep asleep.
 *   - For Edge Esmeralda attendees (Healdsburg PST), 02:00 PST is
 *     soundly asleep through the entire conference window (May 30–Jun 21).
 *   - EU users are at work, not chatting with their personal AI agent.
 *   - APAC is the cost (evening hours), but the cohort is minimal today.
 *
 * RandomizedDelaySec=1800 spreads ~160 fleet VMs across 30 minutes at
 * ~1 restart per 11 seconds — well below any Telegram getUpdates rate
 * limit, well below any LLM provider per-second cap.
 *
 * Persistent=true handles missed firings (VM was powered off at the
 * scheduled time). systemd will fire the most recent missed instance
 * on next boot. Bounded: it does NOT replay a backlog, only the most
 * recent miss.
 *
 * UTC suffix on OnCalendar is load-bearing — the VM's local timezone
 * may not match UTC (`user_timezone` is set per-customer for agent
 * personalization, not for system scheduling). Without the suffix,
 * the schedule would silently drift with any system-tz change.
 */
export const DAILY_RESTART_TIMER_UNIT = `# Generated by InstaClaw platform — DO NOT EDIT MANUALLY.
# Source: instaclaw/lib/systemd-templates.ts (constant DAILY_RESTART_TIMER_UNIT).
# Deployed by: instaclaw/lib/vm-manifest.ts:files[] (mode: overwrite).
# Manual edits are reverted on the next file-drift cron tick (~15 min).
#
# Schedules a daily graceful restart of openclaw-gateway. See CLAUDE.md
# Rule 70 for the full rationale on window selection and jitter sizing.

[Unit]
Description=Schedule daily openclaw-gateway restart at 09:00 UTC (+/- 30min jitter)
Documentation=https://github.com/coopergwrenn/clawlancer/blob/main/CLAUDE.md

[Timer]
# 09:00 UTC = 05:00 EST = 02:00 PST = 10:00 CET = 18:00 JST.
# Selected as the global minimum of platform traffic for the current
# user base composition. The explicit "UTC" suffix is required: VMs
# have a per-customer user_timezone in their config (used by agent
# logic for things like calendar formatting), which is NOT the system
# timezone but might propagate in subtle ways. Naming UTC explicitly
# makes this immune to that class of drift.
OnCalendar=*-*-* 09:00:00 UTC

# Spread restarts across a 30-minute uniform-random window. At ~160
# healthy fleet VMs this is ~1 restart every 11 seconds — comfortably
# below Telegram getUpdates rate limits (per-bot, not per-IP) and
# below the per-second cap of every upstream LLM provider. The jitter
# also serves as an implicit grace period for the 0.05%/day case of
# a user being mid-conversation at the scheduled time: their VM may
# happen to fire 23 minutes later when they're idle.
RandomizedDelaySec=1800

# If the VM was powered off at the scheduled time (maintenance window
# overlap, Linode-side reboot, host upgrade), fire the most recent
# missed instance once on next boot. Bounded — only the most recent
# miss is replayed, not a backlog of missed days.
Persistent=true

# Explicit unit reference. Not strictly required (systemd defaults to
# <name>.service for <name>.timer), but explicit is safer and makes
# the timer→service relationship visible at file inspection time.
Unit=openclaw-daily-restart.service

[Install]
WantedBy=timers.target
`;
