/**
 * lib/toolrouter-wrapper-script.ts
 *
 * The K.4 stdio wrapper that sits between OpenClaw and the real
 * `toolrouter` binary on each VM. Exported as a string constant for
 * the reconciler to deploy to ~/.openclaw/scripts/toolrouter-wrapper.mjs
 * via stepFiles (with Rule 23 sentinels).
 *
 * Architectural role: trustless allocation enforcement. The wrapper is
 * trusted (it runs on our infrastructure, the agent has no shell access
 * to bypass it) and observes the upstream MCP response from
 * toolrouter.world (which the agent has no ability to fabricate). Every
 * tool call gets a record-usage POST with the upstream-verified
 * structuredContent block (charged, trace_id, path, etc.). See
 * /tmp/tr-fetch/package/dist/server.js:776-790 for the source-of-truth
 * fields the binary surfaces in MCP responses.
 *
 * Failure-mode envelope (Cooper, ultrathink session):
 *   - Wrapper crash → child dies with it → OpenClaw respawns on next call
 *   - InstaClaw unreachable → swallow, log to stderr, cron backstop
 *     reconciles via GET /v1/requests audit-log poll
 *   - Child exits unexpectedly → propagate exit code so OpenClaw respawns
 *   - SIGTERM/SIGINT → forward to child, brief wait, exit cleanly
 *   - OOM-class large MCP message → skip observation, passthrough continues
 *   - Concurrent tool calls → matched by JSON-RPC id, map TTL=5min, cap=1000
 *   - Content-Length vs NDJSON framing → auto-detect per session,
 *     mirrors toolrouter binary's dispatcher
 *
 * Passthrough invariant: bytes get push()'d to the destination BEFORE
 * any observation logic runs. Observation is wrapped in try/catch.
 * Passthrough must never throw, never block, never be conditional on
 * parse success.
 *
 * Sentinels for Rule 23 deployment guard:
 *   - TOOLROUTER_WRAPPER_V1 (version tag)
 *   - toolrouter-wrapper started (startup log line)
 *   - record-usage POST (the action that defines the wrapper)
 */

export const TOOLROUTER_WRAPPER_MJS = `#!/usr/bin/env node
// toolrouter-wrapper.mjs — K.4 stdio wrapper. Sentinel: TOOLROUTER_WRAPPER_V1.
//
// Sits between OpenClaw and the real \`toolrouter\` binary. Pure stdio
// passthrough + observation. The agent cannot bypass this wrapper because
// OpenClaw spawns it directly via mcp.servers.toolrouter.command and the
// agent has no shell access to the VM.
//
// Source of truth: instaclaw/lib/toolrouter-wrapper-script.ts
// Do not edit this file directly on the VM — file-drift cron will
// overwrite it on the next reconcile tick.

import { spawn } from "node:child_process";
import { Transform } from "node:stream";
import path from "node:path";
import os from "node:os";
import fs from "node:fs";
import { monitorEventLoopDelay } from "node:perf_hooks";
// FIRSTCALL_DIAG_V1 — first-call failure forensics (Rule 23 sentinel). Pure
// observation: captures the EXACT child error + system state on a tool_error,
// to root-cause the intermittent first-call bounce. Zero behavior change —
// all capture runs in the observation handlers AFTER passthrough push, fully
// guarded; if any of it throws it can never affect a tool call. Static import
// (perf_hooks is a Node core module) so module-init timing is unchanged; the
// monitor's construction + every read is itself try/caught.

// Resolve the toolrouter binary. OpenClaw spawns this wrapper with a
// stripped env (only the keys we set in mcp.servers.toolrouter.env — no
// PATH). So spawning a bare-name child fails ENOENT. Two-rule resolver:
//   - If TOOLROUTER_WRAPPER_CHILD_CMD contains a path separator, trust it
//     verbatim (operator override, e.g., for testing).
//   - Otherwise (default "toolrouter"), resolve sibling-to-process.execPath.
//     The wrapper is launched via \`node\` and toolrouter is installed as
//     an NVM sibling-of-node symlink, so dirname(execPath)/toolrouter is
//     guaranteed to exist on every fleet VM regardless of node version.
// Sentinel: BINARY_RESOLVED_BY_EXECPATH (Rule 23 — refuses stale-cache deploys).
const TOOLROUTER_BINARY_ENV = process.env.TOOLROUTER_WRAPPER_CHILD_CMD || "toolrouter";
const TOOLROUTER_BINARY = TOOLROUTER_BINARY_ENV.includes("/")
  ? TOOLROUTER_BINARY_ENV
  : path.join(path.dirname(process.execPath), TOOLROUTER_BINARY_ENV); // BINARY_RESOLVED_BY_EXECPATH
const INSTACLAW_API_URL = process.env.INSTACLAW_API_URL || "https://instaclaw.io";
const RECORD_USAGE_PATH = "/api/agent/toolrouter/record-usage";
const POST_TIMEOUT_MS = 2_000;
const MAX_OBSERVATION_BYTES = 1_000_000; // skip observing >1MB messages
const PENDING_TTL_MS = 5 * 60 * 1000;
const PENDING_MAX = 1000;
const PENDING_SWEEP_MS = 60 * 1000;

// ── Structured logging to stderr (OpenClaw captures + forwards) ──
function log(level, msg, extra) {
  const ts = new Date().toISOString();
  try {
    const tail = extra ? " " + JSON.stringify(extra) : "";
    process.stderr.write(\`[toolrouter-wrapper] \${ts} \${level}: \${msg}\${tail}\\n\`);
  } catch {
    // Even logging can fail (EPIPE). Swallow — never break the call.
  }
}

// Top-level guard: if anything unexpected throws, log and exit 1 so
// OpenClaw respawns. The pass-through is in a Transform that never
// throws synchronously, so this should only fire on init errors.
process.on("uncaughtException", (err) => {
  log("error", "uncaughtException: " + String(err?.message || err).slice(0, 240));
  process.exit(1);
});
process.on("unhandledRejection", (reason) => {
  log("error", "unhandledRejection: " + String(reason).slice(0, 240));
  // Don't exit on rejection — reject is non-fatal for our use case
  // (most rejections are from the fire-and-forget POST).
});

// ── Spawn child: real toolrouter binary ──
const child = spawn(TOOLROUTER_BINARY, [], {
  env: process.env,
  stdio: ["pipe", "pipe", "pipe"],
});

child.on("error", (err) => {
  log("error", "child spawn error: " + String(err?.message || err).slice(0, 240));
  process.exit(127);
});

let childExitCode = null;
child.on("exit", (code, signal) => {
  childExitCode = code ?? (signal ? 1 : 0);
  // Brief delay to let stdout flush, then propagate.
  setTimeout(() => process.exit(childExitCode), 50);
});

// Stderr passthrough — OpenClaw might log it.
child.stderr.pipe(process.stderr);

// Signal forwarding.
for (const sig of ["SIGTERM", "SIGINT"]) {
  process.on(sig, () => {
    try { child.kill(sig); } catch { /* swallow */ }
    setTimeout(() => process.exit(0), 1000);
  });
}

// ── Pending tool-call correlation map: id → { name, args, startedAt } ──
const pending = new Map();

setInterval(() => {
  const cutoff = Date.now() - PENDING_TTL_MS;
  for (const [id, entry] of pending) {
    if (entry.startedAt < cutoff) pending.delete(id);
  }
  // Hard cap: evict oldest (Map preserves insertion order).
  while (pending.size > PENDING_MAX) {
    const oldest = pending.keys().next().value;
    pending.delete(oldest);
  }
}, PENDING_SWEEP_MS).unref();

// ── FIRSTCALL_DIAG_V1: first-call failure forensics (pure observation) ──
// Captures, on each tool_error, the exact child error + system state so the
// next real failure tells us the root cause with certainty. Lightweight
// fields (spawn age / call seq / prior successes) ride on EVERY record-usage
// POST so we can compare the failed call to the warm retry. The rich diag is
// written SYNCHRONOUSLY to a local JSONL (crash-proof: survives a process
// kill that the fire-and-forget POST would not) AND attached to the POST.
const WRAPPER_SPAWN_TS = Date.now();
let callSeq = 0; // increments per observed tools/call (req side)
let priorSuccessCount = 0; // successful tool responses seen so far this spawn
// Lifetime event-loop-delay monitor. For a young wrapper (first-call failures
// have small spawn-age) the lifetime window IS the failure window, so max/p99
// reflect contention around the failure. Construction guarded — null if the
// runtime rejects it.
let eld = null;
try {
  if (typeof monitorEventLoopDelay === "function") {
    eld = monitorEventLoopDelay({ resolution: 20 });
    eld.enable();
  }
} catch { eld = null; }
// Durable local sink. os.homedir() reads the OS user db (works under the
// stripped MCP env that lacks $HOME); fall back to the known fleet home.
let DIAG_FILE = null;
try {
  const home = os.homedir() || process.env.HOME || "/home/openclaw";
  const dir = path.join(home, ".openclaw", "logs");
  try { fs.mkdirSync(dir, { recursive: true }); } catch { /* dir may exist */ }
  DIAG_FILE = path.join(dir, "toolrouter-firstcall-diag.jsonl");
} catch { DIAG_FILE = null; }

// Cheap fields included on EVERY record-usage POST (success + failure).
function liteFields(req) {
  return {
    spawn_age_ms: Date.now() - WRAPPER_SPAWN_TS,
    call_seq: (req && typeof req.seq === "number") ? req.seq : null,
    prior_success_count: priorSuccessCount,
  };
}

// Rich diag built ONLY on a tool_error. Fully defensive — any throw returns a
// minimal object; never propagates.
function buildDiag(req, msg, latency) {
  const d = {
    ts: new Date().toISOString(),
    endpoint: (req && req.name) || null,
    call_seq: (req && typeof req.seq === "number") ? req.seq : null,
    prior_success_count: priorSuccessCount,
    spawn_age_ms: Date.now() - WRAPPER_SPAWN_TS,
    latency_ms: latency,
    child_pid: (typeof child !== "undefined" && child) ? child.pid : null,
  };
  try {
    const result = msg && msg.result;
    d.is_error = !!(result && result.isError === true);
    // MCP tool error text lives in result.content[].text; capture all of it.
    if (result && Array.isArray(result.content)) {
      d.error_text = result.content
        .map((c) => (c && typeof c.text === "string" ? c.text : ""))
        .join(" ")
        .slice(0, 2000);
    } else {
      d.error_text = null;
    }
    d.result_keys = result && typeof result === "object" ? Object.keys(result).slice(0, 20) : null;
    // JSON-RPC protocol error (distinct from a tool-result error).
    if (msg && msg.error) {
      d.rpc_error = { code: msg.error.code ?? null, message: String(msg.error.message ?? "").slice(0, 500) };
    }
    // Capped raw sample for full forensics on anything the fields miss.
    d.raw_result_sample = result !== undefined ? JSON.stringify(result).slice(0, 2000) : null;
  } catch (e) {
    d.diag_build_error = String((e && e.message) || e).slice(0, 200);
  }
  // System state at the moment of failure — proves/disproves CPU contention.
  try {
    d.loadavg = os.loadavg(); // [1m,5m,15m] — VM-wide; [0,0,0] if unsupported
  } catch { d.loadavg = null; }
  try {
    const cu = process.cpuUsage(); // microseconds of CPU since process start
    d.cpu_user_us = cu.user;
    d.cpu_system_us = cu.system;
  } catch { /* leave undefined */ }
  try {
    d.rss_mb = Math.round(process.memoryUsage().rss / 1048576);
  } catch { /* leave undefined */ }
  try {
    if (eld) {
      d.eventloop_p99_ms = +(eld.percentile(99) / 1e6).toFixed(1);
      d.eventloop_max_ms = +(eld.max / 1e6).toFixed(1);
      d.eventloop_mean_ms = +(eld.mean / 1e6).toFixed(1);
    }
  } catch { /* leave undefined */ }
  return d;
}

// Synchronous append so the record survives a process kill. On the rare
// error path only, AFTER the response has already been forwarded — cannot
// delay or mask the call.
function writeDiag(diag) {
  if (!DIAG_FILE) return;
  try {
    fs.appendFileSync(DIAG_FILE, JSON.stringify(diag) + "\\n");
  } catch (e) {
    log("warn", "diag write failed: " + String((e && e.message) || e).slice(0, 120));
  }
}

// ── Fire-and-forget POST to InstaClaw ──
function reportUsage(data) {
  const token = process.env.GATEWAY_TOKEN;
  if (!token) {
    // No auth → skip silently. Cron backstop will reconcile from
    // ToolRouter's audit log within an hour.
    return;
  }

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), POST_TIMEOUT_MS);

  fetch(INSTACLAW_API_URL + RECORD_USAGE_PATH, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": "Bearer " + token,
    },
    body: JSON.stringify(data),
    signal: ctrl.signal,
  })
    .then((res) => {
      if (!res.ok) {
        log("warn", "record-usage POST status " + res.status, { trace_id: data.trace_id });
      }
    })
    .catch((err) => {
      // Network errors, timeouts, DNS failures. Swallow.
      const msg = String(err?.message || err).slice(0, 120);
      log("warn", "record-usage POST failed: " + msg, { trace_id: data.trace_id });
    })
    .finally(() => clearTimeout(timer));
}

// ── MCP framing observer (NDJSON OR Content-Length, auto-detect) ──
// Mirrors the toolrouter binary's dispatcher logic exactly (dist/server.js
// lines 1224-1280). Whatever framing OpenClaw uses, we parse the same way.
//
// CRITICAL: every Transform pushes the chunk through to the destination
// BEFORE attempting any parse. Observation never blocks passthrough.

function makeObserver(onMessage, label) {
  let buf = Buffer.alloc(0);
  let mode = null; // "frame" | "line" | null

  function startsWithFrameHeader(b) {
    const prefix = b.subarray(0, Math.min(b.length, 32)).toString("utf8");
    return /^Content-Length:/i.test(prefix);
  }
  function frameHeaderEnd(b) {
    const crlf = b.indexOf("\\r\\n\\r\\n");
    const lf = b.indexOf("\\n\\n");
    if (crlf === -1 && lf === -1) return null;
    if (crlf !== -1 && (lf === -1 || crlf < lf)) return { index: crlf, length: 4 };
    return { index: lf, length: 2 };
  }

  function tryObserve(jsonText) {
    try {
      const msg = JSON.parse(jsonText);
      onMessage(msg);
    } catch {
      // Malformed JSON — pass-through already happened, just skip parse.
    }
  }

  function drain() {
    while (buf.length) {
      if (mode === "frame" || (mode === null && startsWithFrameHeader(buf))) {
        const headerEnd = frameHeaderEnd(buf);
        if (!headerEnd) return; // need more bytes
        const header = buf.subarray(0, headerEnd.index).toString("utf8");
        const match = header.match(/^Content-Length:\\s*(\\d+)\\s*$/im);
        if (!match) {
          // Malformed frame header — reset to avoid spinning.
          buf = Buffer.alloc(0);
          mode = null;
          return;
        }
        const contentLength = Number(match[1]);
        const bodyStart = headerEnd.index + headerEnd.length;
        const bodyEnd = bodyStart + contentLength;
        if (buf.length < bodyEnd) return; // need more bytes
        if (contentLength <= MAX_OBSERVATION_BYTES) {
          const body = buf.subarray(bodyStart, bodyEnd).toString("utf8");
          tryObserve(body);
        }
        buf = buf.subarray(bodyEnd);
        mode = "frame";
        continue;
      }
      // NDJSON path
      const nl = buf.indexOf("\\n");
      if (nl === -1) return;
      if (nl <= MAX_OBSERVATION_BYTES) {
        const line = buf.subarray(0, nl).toString("utf8").replace(/\\r$/, "").trim();
        if (line) tryObserve(line);
      }
      buf = buf.subarray(nl + 1);
      mode = "line";
    }
  }

  return new Transform({
    transform(chunk, _enc, cb) {
      // Pass-through FIRST. Bytes flow regardless of observation outcome.
      this.push(chunk);
      try {
        buf = Buffer.concat([buf, Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)]);
        // Runaway-buffer reset (e.g., partial 100MB message). Passthrough
        // already happened, so dropping the observation buffer is safe.
        if (buf.length > MAX_OBSERVATION_BYTES * 4) {
          buf = Buffer.alloc(0);
          mode = null;
        }
        drain();
      } catch (e) {
        const msg = String(e?.message || e).slice(0, 120);
        log("warn", label + " observer error: " + msg);
      }
      cb();
    },
  });
}

// ── Message handlers ──

function onClientMessage(msg) {
  // Client (OpenClaw) → Server (toolrouter). We care about tools/call.
  if (!msg || typeof msg !== "object") return;
  if (msg.method !== "tools/call") return;
  if (msg.id === undefined || msg.id === null) return; // notifications can't correlate
  const name = msg.params && msg.params.name;
  const args = msg.params && msg.params.arguments;
  if (typeof name !== "string") return;

  callSeq += 1; // FIRSTCALL_DIAG_V1: which call number in this spawn lifetime
  pending.set(msg.id, {
    name,
    args: typeof args === "object" && args !== null ? args : null,
    startedAt: Date.now(),
    seq: callSeq,
  });
}

function onServerMessage(msg) {
  // Server (toolrouter) → Client (OpenClaw). Response or error envelope.
  if (!msg || typeof msg !== "object") return;
  if (msg.id === undefined || msg.id === null) return;

  const req = pending.get(msg.id);
  if (!req) return; // not a tracked tools/call (could be initialize, tools/list, etc.)
  pending.delete(msg.id);

  const latency = Date.now() - req.startedAt;
  const result = msg.result;
  const sc = result && result.structuredContent;

  if (!sc) {
    // No structuredContent — an error response from the binary (or a tool
    // that doesn't surface metadata). FIRSTCALL_DIAG_V1: this is the failure
    // pattern we're root-causing. Build + persist the rich diag (sync local
    // file = crash-proof) and attach it to the POST. All guarded; the
    // response has ALREADY been forwarded by the Transform's push() above, so
    // none of this can delay or mask the call.
    let diag = null;
    try {
      diag = buildDiag(req, msg, latency);
      writeDiag(diag);
    } catch { /* observation must never throw */ }
    reportUsage({
      endpoint_id: req.name,
      trace_id: null,
      charged: false,
      path: "unknown",
      status_code: null,
      credit_captured_usd: null,
      latency_ms: latency,
      error_class: result && result.isError === true ? "tool_error" : "no_metadata",
      args: req.args,
      weight_claimed: null,
      ...liteFields(req),
      ...(diag ? { diag } : {}),
    });
    return;
  }

  // Success. Snapshot the prior-success count (value BEFORE this success) so
  // the lite fields read consistently, then increment so a later failure
  // knows exactly how many calls succeeded before it (cold-start proof).
  const priorBefore = priorSuccessCount;
  priorSuccessCount += 1;
  reportUsage({
    endpoint_id: sc.endpoint_id || req.name,
    trace_id: typeof sc.trace_id === "string" ? sc.trace_id : null,
    charged: typeof sc.charged === "boolean" ? sc.charged : false,
    path: typeof sc.path === "string" ? sc.path : "unknown",
    status_code: typeof sc.status_code === "number" ? sc.status_code : null,
    credit_captured_usd: typeof sc.credit_captured_usd === "number" ? sc.credit_captured_usd : null,
    latency_ms: latency,
    error_class: result.isError === true ? "tool_error" : null,
    args: req.args,
    weight_claimed: null,
    spawn_age_ms: Date.now() - WRAPPER_SPAWN_TS,
    call_seq: typeof req.seq === "number" ? req.seq : null,
    prior_success_count: priorBefore,
  });
}

// ── Wire up the bidirectional pipe with observation ──
const stdinObs = makeObserver(onClientMessage, "client");
const stdoutObs = makeObserver(onServerMessage, "server");

process.stdin.pipe(stdinObs).pipe(child.stdin);
child.stdout.pipe(stdoutObs).pipe(process.stdout);

// Belt-and-suspenders: explicit handlers for end / EPIPE.
process.stdin.on("end", () => {
  try { child.stdin.end(); } catch { /* swallow */ }
});
process.stdout.on("error", (err) => {
  if (err && err.code === "EPIPE") process.exit(0);
});
child.stdin.on("error", (err) => {
  // Child closed its stdin (rare). Don't crash the wrapper.
  log("warn", "child.stdin error: " + String(err?.message || err).slice(0, 120));
});

log("info", "toolrouter-wrapper started", { childPid: child.pid, binary: TOOLROUTER_BINARY });
`;
