-- ─────────────────────────────────────────────────────────────────────
-- Consensus 2026 — Live Events skill registration.
--
-- Adds a single row to instaclaw_skills representing the Consensus 2026
-- intent matching feature as a user-toggleable skill. Skills page UI
-- already renders any row in this table; only data ships here. The
-- "live-events" category is registered in app/(dashboard)/skills/page.tsx
-- in a sibling commit.
--
-- Critical defaults:
--   is_default = false → existing users do NOT see this enabled by default.
--                        The 98% of users not going to Consensus get nothing.
--                        Auto-enable happens only via:
--                          - /api/partner/tag with partner='consensus_2026' or
--                            partner='edge_city' (POSTed when user signs up
--                            via /consensus or /edge-city, or by operator)
--                          - the agent flipping the skill on after detecting
--                            organic strong-signal Consensus intent in chat
--                          - manual user toggle on the Skills page
--   tier_minimum = 'starter' → available across all paid tiers
--   requires_restart = true → consistent with other skills; reconciler
--                             handles install + cron registration
--
-- This is the template for future conferences (Bitcoin 2026, Token2049,
-- Devcon, etc.). Each new event is one INSERT here + a corresponding
-- partner allow-list entry in /api/partner/tag.
-- ─────────────────────────────────────────────────────────────────────

INSERT INTO instaclaw_skills (
  slug,
  name,
  description,
  long_description,
  icon,
  category,
  item_type,
  requires_restart,
  requires_api_key,
  tier_minimum,
  is_default,
  sort_order,
  status
) VALUES (
  'consensus-2026',
  'Consensus 2026 Matching',
  'Find the right people to meet at Consensus 2026 (May 5-7, Miami)',
  'Your agent runs a matching pipeline every 30 minutes during the conference, scoring 1-3 attendees worth meeting based on weeks of memory of you. Match rationale is generated by your own agent — not a generic recommender — citing specific things from your history. XMTP intro flow ships Wednesday.',
  '🤝',
  'live-events',
  'skill',
  false,         -- requires_restart — live-events skills are gated by runtime
                 -- check in their own cron, not by skill-dir presence. Toggling
                 -- doesn't need a gateway restart; the pipeline picks up the
                 -- new state at the next cron tick (≤30 min). No SSH needed.
  false,         -- requires_api_key
  'starter',
  false,         -- is_default — explicit opt-in only
  1,             -- sort_order within live-events category
  'active'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  sort_order = EXCLUDED.sort_order,
  status = EXCLUDED.status;
-- ON CONFLICT keeps is_default = false on re-run; intentional. The first
-- successful insert sets is_default; subsequent runs preserve it.
