/**
 * Build-time generator for lib/matchpool-scripts-content.ts.
 *
 * Why: lib/matchpool-scripts.ts originally lazy-loaded 7 Python scripts
 * via fs.readFileSync(path.resolve(__dirname, "..", "scripts", filename)).
 * Next 15/16's outputFileTracingIncludes was supposed to bundle those
 * .py files into the serverless function output, but no glob shape we
 * tried (individual paths, mid-name wildcards, recursive **\/*.py,
 * recursive **\/*) was actually making Vercel copy them to /ROOT/instaclaw/
 * scripts/... at deploy time. Locally `.next/server/.../route.js.nft.json`
 * showed all 7 traced; Vercel deploy bundle didn't include them. This
 * blocked the cv=82 cohort (86 VMs) from advancing past v82.
 *
 * Fix: embed the .py file contents directly into a TS file as string
 * exports. Compiles into the JS bundle through the normal import graph
 * — no fs.readFileSync, no outputFileTracingIncludes, no Vercel-specific
 * bundling magic. Run as a prebuild step so the .ts file always reflects
 * the latest .py source.
 */
import * as fs from "fs";
import * as path from "path";

const SCRIPTS_DIR = path.resolve(__dirname, "..", "scripts");
const OUT_FILE = path.resolve(__dirname, "..", "lib", "matchpool-scripts-content.ts");

const FILES: Array<{ key: string; filename: string }> = [
  { key: "CONSENSUS_MATCH_PIPELINE_PY", filename: "consensus_match_pipeline.py" },
  { key: "CONSENSUS_MATCH_RERANK_PY", filename: "consensus_match_rerank.py" },
  { key: "CONSENSUS_MATCH_DELIBERATE_PY", filename: "consensus_match_deliberate.py" },
  { key: "CONSENSUS_MATCH_CONSENT_PY", filename: "consensus_match_consent.py" },
  { key: "CONSENSUS_INTENT_SYNC_PY", filename: "consensus_intent_sync.py" },
  { key: "CONSENSUS_INTENT_EXTRACT_PY", filename: "consensus_intent_extract.py" },
  { key: "CONSENSUS_MATCH_SKILL_TOGGLE_PY", filename: "consensus_match_skill_toggle.py" },
];

const header = `/**
 * AUTO-GENERATED by scripts/_generate-matchpool-content.ts.
 * Do NOT edit by hand. Edit the source .py files in scripts/ and re-run
 * the generator (\`npm run prebuild\` or \`npm run build\`).
 *
 * Why this file exists: see scripts/_generate-matchpool-content.ts.
 */

`;

const exports = FILES.map(({ key, filename }) => {
  const filePath = path.join(SCRIPTS_DIR, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`generate-matchpool-content: source file missing: ${filePath}`);
  }
  const content = fs.readFileSync(filePath, "utf-8");
  // Base64 encode to avoid every escaping concern (template-literal backticks,
  // ${} interpolations, backslashes). Decode at module load.
  const b64 = Buffer.from(content, "utf-8").toString("base64");
  return `// source: scripts/${filename} (${content.length} chars)\nexport const ${key} = Buffer.from(\n  ${JSON.stringify(b64)},\n  "base64",\n).toString("utf-8");`;
}).join("\n\n");

fs.writeFileSync(OUT_FILE, header + exports + "\n");
console.log(`generate-matchpool-content: wrote ${OUT_FILE} (${FILES.length} files)`);
