/**
 * Build-time generator for lib/gbrain-scripts-content.ts.
 *
 * Why: same Vercel-nft trap that the matchpool team hit (see
 * scripts/_generate-matchpool-content.ts header). fs.readFileSync of files
 * inside scripts/ + outputFileTracingIncludes globs locally show traced, but
 * the Vercel deploy bundle silently doesn't include them. Embedding the file
 * contents directly into a TS file routes them through the normal import
 * graph — no fs, no tracer, no surprises at runtime.
 *
 * Sources:
 *   - scripts/install-gbrain.sh                              (Phase A-I per-VM installer)
 *   - scripts/verify-gbrain-mcp.py                           (Phase H put_page→query round-trip)
 *   - scripts/pglite-checkpoint.sh                           (Phase I CHECKPOINT cron + ExecStop hook)
 *   - scripts/gbrain-patches/0001-add-checkpoint-mcp-tool.patch (Phase C2 instaclaw patch)
 *
 * The last two are companion files install-gbrain.sh looks for at /tmp/<basename>
 * (or alongside itself) — added 2026-05-20 after canary surfaced the silent-
 * degradation bug where the TS reconciler uploaded ONLY install-gbrain.sh +
 * verify-gbrain-mcp.py, causing Phase C2 (patch) + Phase I (cron + drop-in)
 * to skip with WARN-but-exit-0, leaving 15/15 canary VMs missing the
 * checkpoint cron + Rule 54 corruption prevention.
 *
 * Output: lib/gbrain-scripts-content.ts with INSTALL_GBRAIN_SH +
 * VERIFY_GBRAIN_MCP_PY + PGLITE_CHECKPOINT_SH + GBRAIN_CHECKPOINT_PATCH
 * string exports (base64-decoded at module load to avoid every TS escaping
 * concern — template literals, backticks, ${}, backslashes).
 *
 * Run as part of `npm run build` (and `npm run prebuild` by callers that
 * want a fresh snapshot). The .ts file is regenerated every time.
 */
import * as fs from "fs";
import * as path from "path";

const SCRIPTS_DIR = path.resolve(__dirname, "..", "scripts");
const OUT_FILE = path.resolve(__dirname, "..", "lib", "gbrain-scripts-content.ts");

const FILES: Array<{ key: string; filename: string }> = [
  { key: "INSTALL_GBRAIN_SH", filename: "install-gbrain.sh" },
  { key: "VERIFY_GBRAIN_MCP_PY", filename: "verify-gbrain-mcp.py" },
  { key: "PGLITE_CHECKPOINT_SH", filename: "pglite-checkpoint.sh" },
  { key: "GBRAIN_CHECKPOINT_PATCH", filename: "gbrain-patches/0001-add-checkpoint-mcp-tool.patch" },
];

const header = `/**
 * AUTO-GENERATED by scripts/_generate-gbrain-content.ts.
 * Do NOT edit by hand. Edit the source files in scripts/ and re-run
 * the generator (\`npm run build\` runs it automatically).
 *
 * Why this file exists: see scripts/_generate-gbrain-content.ts.
 */

`;

const exports = FILES.map(({ key, filename }) => {
  const filePath = path.join(SCRIPTS_DIR, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`generate-gbrain-content: source file missing: ${filePath}`);
  }
  const content = fs.readFileSync(filePath, "utf-8");
  const b64 = Buffer.from(content, "utf-8").toString("base64");
  return `// source: scripts/${filename} (${content.length} chars)\nexport const ${key} = Buffer.from(\n  ${JSON.stringify(b64)},\n  "base64",\n).toString("utf-8");`;
}).join("\n\n");

fs.writeFileSync(OUT_FILE, header + exports + "\n");
console.log(`generate-gbrain-content: wrote ${OUT_FILE} (${FILES.length} files)`);
